"""Update personal guarantor table and business

Revision ID: 4092369dbffd
Revises: 584209b48b65
Create Date: 2026-01-04 22:18:52.294367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4092369dbffd'
down_revision: Union[str, Sequence[str], None] = '584209b48b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_lender_policy_id'), table_name='business')
    op.drop_constraint(op.f('business_lender_policy_id_fkey'), 'business', type_='foreignkey')
    op.drop_column('business', 'lender_policy_id')
    op.drop_index(op.f('ix_personal_guarantor_lender_policy_id'), table_name='personal_guarantor')
    op.drop_constraint(op.f('personal_guarantor_lender_policy_id_fkey'), 'personal_guarantor', type_='foreignkey')
    op.drop_column('personal_guarantor', 'lender_policy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_guarantor', sa.Column('lender_policy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('personal_guarantor_lender_policy_id_fkey'), 'personal_guarantor', 'lender_policy', ['lender_policy_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_personal_guarantor_lender_policy_id'), 'personal_guarantor', ['lender_policy_id'], unique=False)
    op.add_column('business', sa.Column('lender_policy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('business_lender_policy_id_fkey'), 'business', 'lender_policy', ['lender_policy_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_business_lender_policy_id'), 'business', ['lender_policy_id'], unique=False)
    # ### end Alembic commands ###
