"""Add policy tables retry

Revision ID: 45956057b0ed
Revises: a20d036b9732
Create Date: 2026-01-03 21:43:05.939886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45956057b0ed'
down_revision: Union[str, Sequence[str], None] = 'a20d036b9732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lender_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lender.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lender_policy_id'), 'lender_policy', ['id'], unique=False)
    op.create_index(op.f('ix_lender_policy_lender_id'), 'lender_policy', ['lender_id'], unique=False)
    op.create_table('policy_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.String(), nullable=False),
    sa.Column('operator', sa.Enum('EQUAL', 'NOT_EQUAL', 'GREATER_THAN', 'LESS_THAN', 'GREATER_THAN_OR_EQUAL', 'LESS_THAN_OR_EQUAL', 'NOT_IN', 'IN', 'LIKE', 'NOT_LIKE', 'IS', 'IS_NOT', name='operator_type'), nullable=False),
    sa.Column('lender_policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lender_policy_id'], ['lender_policy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rule_id'), 'policy_rule', ['id'], unique=False)
    op.create_index(op.f('ix_policy_rule_lender_policy_id'), 'policy_rule', ['lender_policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_rule_lender_policy_id'), table_name='policy_rule')
    op.drop_index(op.f('ix_policy_rule_id'), table_name='policy_rule')
    op.drop_table('policy_rule')
    op.drop_index(op.f('ix_lender_policy_lender_id'), table_name='lender_policy')
    op.drop_index(op.f('ix_lender_policy_id'), table_name='lender_policy')
    op.drop_table('lender_policy')
    # ### end Alembic commands ###
