"""Addition of business and personal guarantor tables

Revision ID: 5643ec5651c4
Revises: ebf3faf74a92
Create Date: 2026-01-04 21:53:02.210227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5643ec5651c4'
down_revision: Union[str, Sequence[str], None] = 'ebf3faf74a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geographic_location', sa.String(), nullable=False),
    sa.Column('industry_type', sa.String(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('business_duration', sa.Integer(), nullable=False),
    sa.Column('paynet_score', sa.Integer(), nullable=False),
    sa.Column('lender_policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lender_policy_id'], ['lender_policy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_id'), 'business', ['id'], unique=False)
    op.create_index(op.f('ix_business_lender_policy_id'), 'business', ['lender_policy_id'], unique=False)
    op.create_table('personal_guarantor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fico_score', sa.Integer(), nullable=False),
    sa.Column('trade_lines', sa.Integer(), nullable=False),
    sa.Column('credit_history_flags', sa.String(), nullable=False),
    sa.Column('lender_policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lender_policy_id'], ['lender_policy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_guarantor_id'), 'personal_guarantor', ['id'], unique=False)
    op.create_index(op.f('ix_personal_guarantor_lender_policy_id'), 'personal_guarantor', ['lender_policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_guarantor_lender_policy_id'), table_name='personal_guarantor')
    op.drop_index(op.f('ix_personal_guarantor_id'), table_name='personal_guarantor')
    op.drop_table('personal_guarantor')
    op.drop_index(op.f('ix_business_lender_policy_id'), table_name='business')
    op.drop_index(op.f('ix_business_id'), table_name='business')
    op.drop_table('business')
    # ### end Alembic commands ###
