"""Update personal guarantor table

Revision ID: 584209b48b65
Revises: 5643ec5651c4
Create Date: 2026-01-04 22:12:06.589587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584209b48b65'
down_revision: Union[str, Sequence[str], None] = '5643ec5651c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_guarantor', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_guarantor', 'name')
    # ### end Alembic commands ###
