"""Update in policy rule table

Revision ID: 5afed5358ec4
Revises: e64cb0762666
Create Date: 2026-01-04 12:02:40.103987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5afed5358ec4"
down_revision: Union[str, Sequence[str], None] = "e64cb0762666"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "policy_rule", sa.Column("error_message", sa.String(), nullable=False)
    )

    # Create the requirement_type enum explicitly for Postgres
    requirement_type_enum = sa.Enum("HARD_STOP", "SOFT_MATCH", name="requirement_type")
    requirement_type_enum.create(op.get_bind())

    op.add_column(
        "policy_rule",
        sa.Column("requirement_type", requirement_type_enum, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("policy_rule", "requirement_type")

    # Drop the requirement_type enum explicitly
    requirement_type_enum = sa.Enum(name="requirement_type")
    requirement_type_enum.drop(op.get_bind())

    op.drop_column("policy_rule", "error_message")
    # ### end Alembic commands ###
