"""Addition of field in matching engine.

Revision ID: 5f4e530d8b20
Revises: 65dad80c761a
Create Date: 2026-01-05 01:17:19.338604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4e530d8b20'
down_revision: Union[str, Sequence[str], None] = '65dad80c761a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_engine', sa.Column('loan_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_engine', 'loan_amount')
    # ### end Alembic commands ###
