"""Addition of field in lender policy.

Revision ID: 65dad80c761a
Revises: abbcc3d19d95
Create Date: 2026-01-05 01:14:08.753422

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65dad80c761a"
down_revision: Union[str, Sequence[str], None] = "abbcc3d19d95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lender_policy", sa.Column("loan_amount", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lender_policy", "loan_amount")
    # ### end Alembic commands ###
