"""Addition of matching engine

Revision ID: abbcc3d19d95
Revises: 686c7f01f25d
Create Date: 2026-01-04 22:31:04.644582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbcc3d19d95'
down_revision: Union[str, Sequence[str], None] = '686c7f01f25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eligibility', sa.Enum('YES', 'NO', name='yes_no_enum'), nullable=False),
    sa.Column('matching_tier', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('lender_policy_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('personal_guarantor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['lender_policy_id'], ['lender_policy.id'], ),
    sa.ForeignKeyConstraint(['personal_guarantor_id'], ['personal_guarantor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_engine_id'), 'matching_engine', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matching_engine_id'), table_name='matching_engine')
    op.drop_table('matching_engine')
    # ### end Alembic commands ###
