"""Remove loan amount from lender policy

Revision ID: bb0ffeb17399
Revises: 5f4e530d8b20
Create Date: 2026-01-05 01:17:54.880067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0ffeb17399'
down_revision: Union[str, Sequence[str], None] = '5f4e530d8b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lender_policy', 'loan_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lender_policy', sa.Column('loan_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
