"""Update in lender policy

Revision ID: e64cb0762666
Revises: 45956057b0ed
Create Date: 2026-01-03 21:46:53.598800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e64cb0762666'
down_revision: Union[str, Sequence[str], None] = '45956057b0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lender_policy', sa.Column('file_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lender_policy', 'file_path')
    # ### end Alembic commands ###
