"""Update enum for operator

Revision ID: ebf3faf74a92
Revises: 5afed5358ec4
Create Date: 2026-01-04 12:07:29.055845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebf3faf74a92"
down_revision: Union[str, Sequence[str], None] = "5afed5358ec4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE operator ADD VALUE 'CONTAINS'")
    op.execute("ALTER TYPE operator ADD VALUE 'NOT_CONTAINS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE operator DROP VALUE 'CONTAINS'")
    op.execute("ALTER TYPE operator DROP VALUE 'NOT_CONTAINS'")
    # ### end Alembic commands ###
